// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvLDu_3YpQLL3DOsy-KLAmPjisBQP1Tyk',
    appId: '1:907718880353:web:28dfaeebbc3c3e61c18e20',
    messagingSenderId: '907718880353',
    projectId: 'servicelaptop-b5c7a',
    authDomain: 'servicelaptop-b5c7a.firebaseapp.com',
    storageBucket: 'servicelaptop-b5c7a.firebasestorage.app',
    measurementId: 'G-K96SV6P5QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4QMy8fFC_qTtG4rKT1-8--xOsS8PmWM',
    appId: '1:907718880353:android:2e79e719b8eaf085c18e20',
    messagingSenderId: '907718880353',
    projectId: 'servicelaptop-b5c7a',
    storageBucket: 'servicelaptop-b5c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXkGKZcmnkJcmE0EcrtynHcLz0p4sBn8',
    appId: '1:907718880353:ios:094a3adf493ea875c18e20',
    messagingSenderId: '907718880353',
    projectId: 'servicelaptop-b5c7a',
    storageBucket: 'servicelaptop-b5c7a.firebasestorage.app',
    iosBundleId: 'com.example.serviceLaptop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoXkGKZcmnkJcmE0EcrtynHcLz0p4sBn8',
    appId: '1:907718880353:ios:094a3adf493ea875c18e20',
    messagingSenderId: '907718880353',
    projectId: 'servicelaptop-b5c7a',
    storageBucket: 'servicelaptop-b5c7a.firebasestorage.app',
    iosBundleId: 'com.example.serviceLaptop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvLDu_3YpQLL3DOsy-KLAmPjisBQP1Tyk',
    appId: '1:907718880353:web:0e53f2712f5dd82ec18e20',
    messagingSenderId: '907718880353',
    projectId: 'servicelaptop-b5c7a',
    authDomain: 'servicelaptop-b5c7a.firebaseapp.com',
    storageBucket: 'servicelaptop-b5c7a.firebasestorage.app',
    measurementId: 'G-XQPR6V6E0B',
  );
}
